// <auto-generated />
using AlgorythmicsGame.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlgorythmicsGame.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20220525203909_AddedAlgorithmID")]
    partial class AddedAlgorithmID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlgorythmicsGame.Context.OrganizedMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlgorithmId");

                    b.Property<byte?>("Animation")
                        .HasColumnName("DisplayMode")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ArraySize")
                        .HasColumnName("ArraySize")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("InputType")
                        .HasColumnName("InputType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PlayersWaiting")
                        .HasColumnName("PlayersWaiting")
                        .HasColumnType("tinyint");

                    b.Property<string>("SearchTarget")
                        .HasMaxLength(3);

                    b.Property<byte>("Status")
                        .HasColumnName("Type")
                        .HasColumnType("tinyint");

                    b.Property<string>("TeacherInput")
                        .HasMaxLength(30);

                    b.Property<string>("player1")
                        .HasMaxLength(50);

                    b.Property<string>("player2")
                        .HasMaxLength(50);

                    b.HasKey("MatchId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("AlgorythmicsGame.Models.Algorithm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlgorithmNickname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("AlgorithmPicture");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Icon")
                        .IsRequired();

                    b.Property<bool>("IsPublished");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<byte>("Type")
                        .HasColumnName("Type")
                        .HasColumnType("tinyint");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Algorithms");
                });
#pragma warning restore 612, 618
        }
    }
}
